version: '3.7'
services:
  notebookserver:
    build: ./server/
    # image: jupyter/scipy-notebook:ubuntu-18.04
    volumes: 
      - ./work:/home/jovyan/work
      - ./server/flask:/home/jovyan/flask
    ports: 
      - "8888:8888"
      - "5000:5000"
    container_name: notebookserver